### ISSUE TITLE
Support for module workers?

### ISSUE THREAD

**Issue by AlexErrant** [Aslemammad/vite-plugin-cloudflare#23]
Is there support for [module workers](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/)?

If I replace the contents of `examples/basic/worker/index.ts` with

```ts
export default {
  fetch(request) {
    const base = 'https://example.com';
    const statusCode = 301;

    const destination = new URL(request.url, base);
    return Response.redirect(destination.toString(), statusCode);
  },
};
```

I get the following error:

```
SyntaxError: Unexpected token 'export'
    at new Script (node:vm:100:7)
    at VMScriptRunner.runAsScript (/home/alexerrant/vite-plugin-cloudflare/node_modules/.pnpm/@miniflare+runner-vm@2.6.0/node_modules/@miniflare/runner-vm/src/index.ts:22:20)
    at VMScriptRunner.run (/home/alexerrant/vite-plugin-cloudflare/node_modules/.pnpm/@miniflare+runner-vm@2.6.0/node_modules/@miniflare/runner-vm/src/index.ts:84:12)
    at EventTarget.#reload (/home/alexerrant/vite-plugin-cloudflare/node_modules/.pnpm/@miniflare+core@2.6.0/node_modules/@miniflare/core/src/index.ts:748:42)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Aslemammad** [comment]
Hey, Sure! I'll put this on my to-do list! In case you want faster implementation, feel free to sponsor, I got so many issues to implement!
